export const countryObjList = [
  {
    country: 'South Korea',
    countryKR: '대한민국',
    searchKeywords: ['South Korea', 'Korea', 'Republic of Korea', 'ROK'],
    searchKeywordsKR: ['대한민국', '한국', '남한'],
    cities: ['Seoul', 'Busan', 'Jeju'],
    citiesKR: ['서울', '부산', '제주'],
  },
  {
    country: 'France',
    countryKR: '프랑스',
    searchKeywords: ['France', 'French Republic'],
    searchKeywordsKR: ['프랑스'],
    cities: ['Paris', 'Nice', 'Lyon'],
    citiesKR: ['파리', '니스', '리옹'],
  },
  {
    country: 'Japan',
    countryKR: '일본',
    searchKeywords: ['Japan'],
    searchKeywordsKR: ['일본'],
    cities: ['Tokyo', 'Kyoto', 'Osaka'],
    citiesKR: ['도쿄', '교토', '오사카'],
  },
  {
    country: 'United States',
    countryKR: '미국',
    searchKeywords: ['United States', 'USA', 'US', 'America'],
    searchKeywordsKR: ['미국', '아메리카'],
    cities: ['New York', 'Los Angeles', 'San Francisco', 'Las Vegas'],
    citiesKR: ['뉴욕', '로스앤젤레스', '샌프란시스코', '라스베이거스'],
  },
  {
    country: 'United Kingdom',
    countryKR: '영국',
    searchKeywords: ['United Kingdom', 'UK', 'Britain', 'England'],
    searchKeywordsKR: ['영국', '잉글랜드', '브리튼'],
    cities: ['London', 'Edinburgh', 'Manchester'],
    citiesKR: ['런던', '에든버러', '맨체스터'],
  },
  {
    country: 'Italy',
    countryKR: '이탈리아',
    searchKeywords: ['Italy'],
    searchKeywordsKR: ['이탈리아', '이태리'],
    cities: ['Rome', 'Venice', 'Florence', 'Milan'],
    citiesKR: ['로마', '베니스', '피렌체', '밀라노'],
  },
  {
    country: 'Thailand',
    countryKR: '태국',
    searchKeywords: ['Thailand'],
    searchKeywordsKR: ['태국', '타일랜드'],
    cities: ['Bangkok', 'Phuket', 'Chiang Mai'],
    citiesKR: ['방콕', '푸켓', '치앙마이'],
  },
  {
    country: 'Spain',
    countryKR: '스페인',
    searchKeywords: ['Spain'],
    searchKeywordsKR: ['스페인', '에스파냐'],
    cities: ['Barcelona', 'Madrid', 'Seville'],
    citiesKR: ['바르셀로나', '마드리드', '세비야'],
  },
  {
    country: 'Turkey',
    countryKR: '튀르키예',
    searchKeywords: ['Turkey'],
    searchKeywordsKR: ['터키', '튀르키예', '튀르키에'],
    cities: ['Istanbul', 'Cappadocia', 'Antalya'],
    citiesKR: ['이스탄불', '카파도키아', '안탈리아'],
  },
  {
    country: 'Greece',
    countryKR: '그리스',
    searchKeywords: ['Greece'],
    searchKeywordsKR: ['그리스'],
    cities: ['Santorini', 'Athens', 'Mykonos'],
    citiesKR: ['산토리니', '아테네', '미코노스'],
  },
  {
    country: 'Australia',
    countryKR: '호주',
    searchKeywords: ['Australia'],
    searchKeywordsKR: ['호주', '오스트레일리아'],
    cities: ['Sydney', 'Melbourne', 'Brisbane'],
    citiesKR: ['시드니', '멜버른', '브리즈번'],
  },
  {
    country: 'Indonesia',
    countryKR: '인도네시아',
    searchKeywords: ['Indonesia'],
    searchKeywordsKR: ['인도네시아'],
    cities: ['Bali', 'Jakarta', 'Yogyakarta'],
    citiesKR: ['발리', '자카르타', '욕야카르타'],
  },
  {
    country: 'Canada',
    countryKR: '캐나다',
    searchKeywords: ['Canada'],
    searchKeywordsKR: ['캐나다'],
    cities: ['Vancouver', 'Toronto', 'Montreal'],
    citiesKR: ['밴쿠버', '토론토', '몬트리올'],
  },
];

export const countryObj =
  countryObjList[Math.floor(Math.random() * countryObjList.length)];
